### ISSUE TITLE
Cards with missing National Pokedex Numbers

### ISSUE THREAD

**Issue by SiWoC** [PokemonTCG/pokemon-tcg-data#191]
A lot of these have special characters in their name, which could account for a lookup going wrong or something.

id | name | NPN | Remarks
-- | -- | -- | --
ecard2-95 | Mr. Mime | 122 |  
ecard3-81 | Nidoran ? | 29 | Female
ecard3-82 | Nidoran ? | 29 | Female
dp1-90 | Mime Jr. | 439 |  
dpp-DP22 | Mime Jr. | 439 |  
dp2-30 | Mr. Mime | 122 |  
dp3-97 | Nidoran ? | 32 | Male
pl2-28 | Mr. Mime E4 | 122 |  
pl3-37 | Mr. Mime | 122 |  
pl3-115 | Mime Jr. | 439 |  
col1-29 | Mr. Mime | 122 |  
col1-47 | Mime Jr. | 439 |  
bw9-47 | Mr. Mime | 122 |  
xy1-91 | Mr. Mime | 122 |  
xy5-101 | Mr. Mime | 122 |  
xy8-97 | Mr. Mime | 122 |  
g1-52 | Mr. Mime | 122 |  
xy10-67 | Mr. Mime | 122 |  
smp-SM30 | Tapu Koko | 785 |  
smp-SM30a | Tapu Koko | 785 |  
smp-SM31 | Tapu Koko | 785 |  
smp-SM32 | Tapu Bulu-GX | 787 |  
smp-SM33 | Tapu Koko-GX | 785 |  
smp-SM45 | Tapu Lele | 786 |  
smp-SM50 | Tapu Koko-GX | 785 |  
smp-SM61 | Tapu Bulu | 787 |  
smp-SM92 | Tapu Fini | 788 |  
smp-SM152 | Tapu Lele | 786 |  
smp-SM203 | Tapu Fini | 788 |  
sm2-135 | Tapu Koko-GX | 785 |  
sm2-137 | Tapu Lele-GX | 786 |  
sm2-155 | Tapu Lele-GX | 786 |  
sm3-130 | Tapu Bulu-GX | 787 |  
sm3-133 | Tapu Fini-GX | 788 |  
sm3-149 | Tapu Bulu-GX | 787 |  
sm3-152 | Tapu Fini-GX | 788 |  
sm4-89 | Type: Null | 772 |  
sm5-94 | Tapu Lele | 786 |  
sm5-115 | Type: Null | 772 |  
sm8-37 | Tapu Bulu | 787 |  
sm8-85 | Tapu Koko | 785 |  
sm8-150 | Tapu Lele | 786 |  
sm8-151 | Tapu Fini | 788 |  
sm9-51 | Tapu Koko ? | 785 |  Prism Star
sm9-66 | Mr. Mime | 122 |  
sm9-67 | Mr. Mime-GX | 122 |  
det1-11 | Mr. Mime | 122 |  
sm11-53 | Tapu Fini | 788 |  
sm11-69 | Tapu Koko | 785 |  
sm11-183 | Type: Null | 772 |  
sm115-43 | Mr. Mime | 122 |  
sma-SV45 | Type: Null | 772 |  
sm12-183 | Type: Null | 772 |  
swshp-SWSH079 | Galarian Mr. Rime | 866 |  
swsh1-72 | Tapu Koko V | 785 |  
swsh2-37 | Galarian Mr. Mime | 122 |  
swsh2-38 | Galarian Mr. Rime | 866 |  
swsh3-35 | Galarian Mr. Mime | 122 |  
swsh3-36 | Galarian Mr. Rime | 866 |  
swsh3-61 | Tapu Koko | 785 |  
swsh45sv-SV020 | Galarian Mr. Mime | 122 |  
swsh45sv-SV021 | Galarian Mr. Rime | 866 |  
swsh5-16 | Tapu Bulu | 787 |  
swsh5-34 | Galarian Mr. Mime | 122 |  
swsh5-35 | Galarian Mr. Rime | 866 |  
swsh5-50 | Tapu Koko V | 785 |  
swsh5-51 | Tapu Koko VMAX | 785 |  
swsh5-147 | Tapu Koko V | 785 |  
swsh5-166 | Tapu Koko VMAX | 785 |

**Comment by Pepper0ni** [comment]
https://github.com/PokemonTCG/pokemon-tcg-data/pull/257 this should fix it plus some from newer sets.

Please update whatever script you use for this to handle tapus, mimes and the crown tundra mons (and arceus rising mons when they get official numbers, as they'll inevitably become cards)

**Comment by SiWoC** [comment]
I see the commit and all, great job.
But I still get old data when I get it through the api. Isn't that fixed at the same time?
Furthermore... there are some more:

id | name | NPN | Remarks
-- | -- | -- | --
swsh6-40 | Tapu Fini | 788 | 
swsh6-45 | Ice Rider Calyrex V | 898,896 | one or both?
swsh6-46 | Ice Rider Calyrex VMAX | 898,896 | one or both?
swsh6-74 | Shadow Rider Calyrex V | 898,897 | one or both?
swsh6-75 | Shadow Rider Calyrex VMAX | 898,897 | one or both?
swsh6-163 | Ice Rider Calyrex V | 898,896 | one or both?
swsh6-164 | Ice Rider Calyrex V | 898,896 | one or both?
swsh6-171 | Shadow Rider Calyrex V | 898,897 | one or both?
swsh6-172 | Shadow Rider Calyrex V | 898,897 | one or both?
swsh6-202 | Ice Rider Calyrex VMAX | 898,896 | one or both?
swsh6-203 | Ice Rider Calyrex VMAX | 898,896 | one or both?
swsh6-204 | Shadow Rider Calyrex VMAX | 898,897 | one or both?
swsh6-205 | Shadow Rider Calyrex VMAX | 898,897 | one or both?
swsh7-60 | Regieleki | 894
swsh7-124 | Regidrago | 895
cel25c-60_A | Tapu Lele-GX | 786

Bulbapedia describes Ice and Shadow Rider Calyrex as different formes of Calyrex. In that case only 898 might be added.
https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_with_form_differences#Calyrex

**Comment by Pepper0ni** [comment]
Everything in this issue has been resolved, but there's a continued issue with some species not getting IDs on set release. An error in the import script perhaps?

**Comment by adback03** [comment]
@Pepper0ni yes, updating the script as well. Hopefully won't run into this issue in the future.
